menu:
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/realmatthewpeng'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/matt-peng'}

contacts:
- {institution: 'University of California, Santa Barbara', 
  department: 'Computer Science', email: 'mpeng(at)ucsb(dot)edu', image: 'assets/img/contact.jpg'}
